[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.pytest_cache
  | txerpad.egg-info
  | migrations
  | _build
  | build
  | dist
)/
'''
skip-string-normalization=true